INSERT INTO club ([name], [address], [region], [contact], [email], [specials], [description], [link]) VALUES
('Kathys Garage','Alaunstraße 48 01099 Dresden','Neustadt ','0351 6567701','stefan@katysgarage.de','Biergarten','Katys Garage ist ein alternativer Szeneclub im Herzen der Dresdner Neustadt. Die Gäste sind nationale und internationale Studenten, Touristen und Dresdner. Katys Garage versteht sich als weltoffen und tolerant. Das Programmspektrum ist breit gefächert und reicht von Rock bis Elektro. Katys Garage fördert einen respektvollen Umgang im Team und unter den Gästen. Katys Garage distanziert sich von rechtem und linkem Extremismus, Rassismus, Homophobie, Gewaltverherrlichung und Frauenfeindlichkeit.','https://katysgarage.de/'),
('Stolperdiele','Breitscheidstr. 57 01237 Dresden','Außerhalb','01520 2687225','https://www.facebook.com/Stolperdiele','','','www.stolperdiele.de'),
('LOBO','','Neustadt ','','','','',''),
('Kraftwerk Mitte','','Friedrichstadt','','','','',''),
('Downtown','','Neustadt ','','','','',''),
('Rosis','','Neustadt ','','','','',''),
('Altes Wettbüro','','','','','','',''),
('Standesamt ','','','','','','',''),
('Gutzkow','','Uni','','','','',''),
('Club Mensa','','Uni','','','','',''),
('Rösslstube (?)','','Friedrichstadt','','','','',''),
('Sektor','','Industriegelände','','','','',''),
('Objekt klein a','','Industriegelände','','','','',''),
('Blue Dance Club','','Altstadt','','','','',''),
('Gisela ','','Außerhalb','','','','',''),
('Arteum','','Außerhalb','','','','',''),
('Aquarium','','Uni','','','','',''),
('Bärenzwinger (?)','','Altstadt','','','','',''),
('My House','','Elbe','','','','',''),
('TBA','','Neustadt','','','','',''),
('Puro ','','Elbe','','','','',''),
('Club Neu','','Elbe','','','','',''),
('Groovestation','','Neustadt','','','','',''),
('Wu5 ','','Uni','','','','',''),
('Novitatis','','Uni','','','','',''),
('COunt down ','','Uni','','','','',''),
('Club 11','','Uni','','','','',''),
('Traumtänzer','','Uni','','','','',''),
('GAG 18','','Uni','','','','',''),
('Borsi 34','','','','','','',''),
('Hänge Mathe','','','','','','',''),
('Scheune Dresden','','Neustadt','','','','',''),
('Parkhotel Dresden','','','','','','',''),
('Paula','','','','','','',''),
('Showboxx','','Elbe','','','','',''),
('Eventwerk (?)','','','','','','',''),
('Zille','','','','','','',''),
('Chemiefabrik','','','','','','',''),
('Reithalle Straße E','','','','','','',''),
('Alter Schlachthof ','','Elbe','','','','',''),
('Puschkin','','Elbe','','','','',''),
('Tane Ju','','','','','','',''),
('Bunker (?) ','','','','','','',''),
('Beatpol','','','','','','',''),
('Ostpol','','','','','','',''),
('Der Lude','','Neustadt','','','','','');